apiVersion: apps/v1
kind: Deployment
metadata:
  name: fcg-games
  namespace: fcg-games
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fcg-games
  template:
    metadata:
      labels:
        app: fcg-games
    spec:
      containers:
        - name: fcg-games
          image: ${IMAGE}
          ports:
            - containerPort: ${CONTAINER_PORT}
          env:
            - name: ElasticSearchSettings__Endpoint
              valueFrom:
                configMapKeyRef:
                  name: fcg-games-configs
                  key: ElasticSearchEndpoint

            - name: ElasticSearchSettings__Region
              valueFrom:
                configMapKeyRef:
                  name: fcg-games-configs
                  key: ElasticSearchRegion

            - name: ElasticSearchSettings__AccessKey
              valueFrom:
                secretKeyRef:
                  name: fcg-games-secrets
                  key: ElasticSearchAccessKey

            - name: ElasticSearchSettings__Secret
              valueFrom:
                secretKeyRef:
                  name: fcg-games-secrets
                  key: ElasticSearchSecret

            - name: ASPNETCORE_HTTP_PORTS
              value: "${CONTAINER_PORT}"

          livenessProbe:
            httpGet:
              path: /health
              port: ${CONTAINER_PORT}
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
            initialDelaySeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: ${CONTAINER_PORT}
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
            initialDelaySeconds: 10