apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fcg-games-ingress
  namespace: fcg-games
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /games
            pathType: Prefix
            backend:
              service:
                name: fcg-games-service
                port:
                  number: 80
