apiVersion: v1
kind: Secret
metadata:
  name: fcg-games-secrets
  namespace: fcg-games
type: Opaque
data:
  # Valores em Base64 - substitua pelos valores reais
  # Para gerar: echo -n 'seu-valor' | base64
  ElasticSearchAccessKey: "Y2hhbmdlLW1l"  # change-me
  ElasticSearchSecret: "Y2hhbmdlLW1l"      # change-me

