apiVersion: v1
kind: Service
metadata:
  name: fcg-games-service
  namespace: fcg-games
spec:
  selector:
    app: fcg-games
  ports:
    - protocol: TCP
      port: ${SERVICE_PORT}
      targetPort: ${CONTAINER_PORT}
  type: ClusterIP
